# Generated by Django 4.0.4 on 2023-06-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('position', models.CharField(choices=[('JR', 'Junior'), ('MD', 'Middle'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=12)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('experience', models.IntegerField()),
                ('work_start_time', models.TimeField()),
                ('work_end_time', models.TimeField()),
            ],
        ),
    ]
